# Generated by Django 3.1.1 on 2020-10-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_title_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='body',
            new_name='main_body',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='image',
            new_name='main_image',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='title',
            new_name='main_title',
        ),
        migrations.AddField(
            model_name='title',
            name='about_body',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='about_title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
