# Generated by Django 3.1.1 on 2020-10-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20201029_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=50, null=True)),
                ('service_description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='about_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='main_title',
            field=models.CharField(max_length=50),
        ),
    ]
