# Generated by Django 3.1.1 on 2020-10-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_specialization',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
