# Generated by Django 3.1.1 on 2020-10-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_auto_20201029_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='main_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
