# Generated by Django 3.1.1 on 2020-11-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_p_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Online_appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('details', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
