# Generated by Django 3.1.1 on 2020-11-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0012_auto_20201107_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
