# Generated by Django 3.1.1 on 2020-11-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0013_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('Testimonial', models.CharField(max_length=500, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
