# Generated by Django 3.1.1 on 2020-11-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0017_auto_20201107_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='online_appointments',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
